server:
  port: 8085

spring:
  main.banner-mode: 'off'
logging.level:
  root: INFO

ar.vicria.adapter.telegram:
  botUserName:
  botToken:
com.google.calendar:
  clientId:
  projectId:
  clientSecret:
  redirectUris:
  redirectPort: