server:
  port: 8085

spring:
  banner:
    location: classpath:vicria-banner.txt
logging.level:
  root: INFO

ar.vicria.adapter.telegram:
  botUserName:
  botToken:
com.google.calendar:
  clientId:
  projectId:
  clientSecret:
  localhost:
  redirectPort:
  refreshToken:
